### ISSUE TITLE
Watching a Kids profile videos continuously asks to switch profiles

### ISSUE THREAD

**Issue by awanaut** [dmunozv04/iSponsorBlockTV#84] opened 2023-10-22 18:30 UTC
**Describe the bug**
When watching a video using a kids profile, after some period of time causes a popup stating the video cannot be watched under a kids profile and asks to switch to another profile. When stopping the container, the issue goes away. Here is a log entry of stderr: 

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyytlounge/wrapper.py", line 532, in _command
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='RID_OUTSIDE_WINDOW', url=URL('https://www.youtube.com/api/lounge/bc/bind?device=REMOTE_CONTROL&name=iSponsorBlockTV&app=youtube-desktop&loungeIdToken=<token>gsessionid=xxxxxxxxxxxxxx')

**To Reproduce**
1. Open a "kids" profile
2. Watch any available video
3. Wait some period of time
4. See description

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker

**Apple TV (please complete the following information):**
 - Device: Apple TV 4k
 - OS: tvOS 17

**Comment by dmunozv04** [comment] 2023-10-22 18:34
That’s kinda weird. I’ll take a look at kids profiles and try to see what’s wrong here

**Comment by dmunozv04** [comment] 2023-10-22 18:53
I’ve been able to replicate this issue connecting to the TV with a “real” device (a phone), so it seems like the best option would be to detect if the client name matches `TVHTML5_FOR_KIDS` and in that case safely disconnect so it doesn’t trigger that weird popup. 
Feel free to attempt to contact YouTube about this issue, since it also affects “legitimate” devices

**Comment by dmunozv04** [comment] 2023-11-05 17:05
I've published a new `develop` docker image which should fix this issue (it does for me). Please let me know if it works for you @awanaut . You can use this image by replacing `ghcr.io/dmunozv04/isponsorblocktv` with `ghcr.io/dmunozv04/isponsorblocktv:develop` on your docker run/compose

**Comment by awanaut** [comment] 2023-11-12 14:31
All seems to be working! Thanks a bunch!

**Comment by dmunozv04** [comment] 2023-11-12 22:59
That’s great to hear. I’ll go ahead and make a new release soon

**Comment by Clem-** [comment] 2024-05-06 16:07
Hi there, I have the same issue with Youtube Kids and the develop branch isn't fixing the issue :/
Thanks !

**Comment by dmunozv04** [comment] 2024-05-06 16:54
thanks for reporting @Clem- , it’s possible that something internal in YouTube changed since it worked last time I tested it

**Comment by dmunozv04** [comment] 2024-05-06 16:55
Could you please provide details of the TV/console device used and the iSponsorblockTV server?

**Comment by Clem-** [comment] 2024-05-06 17:04
Sure, I'm on an Apple TV 4K and the server is running with docker on a Raspberry Pi 3.

**Comment by danieldabate** [comment] 2024-05-11 12:53
Same happening to me on an LG TV with WebOS

**Comment by reidab** [comment] 2024-05-29 20:52
I think the issue is that the upstream fix made to pyytlounge in https://github.com/FabioGNR/pyytlounge/pull/6 was released in pyytlounge 1.7.0, the workaround in this project was removed in the 2.0.5 release via https://github.com/dmunozv04/iSponsorBlockTV/commit/f4fbbcdff5d8e894998b17ba4526b962a07dd952, but `requirements.txt` for this project is still locked to `pyytlounge==1.6.3`.

I think bumping the dependency version for pyytlounge to 1.7.0 should solve the issue.

**Comment by dmunozv04** [comment] 2024-05-29 21:20
Whoops, that’s my bad. Thanks for catching it. I’ll get a new release published soon

**Comment by danieldabate** [comment] 2024-05-29 21:25
Good catch! I can confirm this fixes the issue! I just tested it locally. Was going to submit a PR, but will wait for you @dmunozv04

**Closed** 2024-05-29 21:39 UTC
Labels: bug
