### ISSUE TITLE
Can’t watch YouTube Shorts

### ISSUE THREAD

**Issue by L041S** [dmunozv04/iSponsorBlockTV#88] opened 2023-10-24 10:00 UTC
**Describe the bug**
Since the latest update to V2 not using the api, I am unable to watch any YT Short on the TV. A message appear "Disconnect device : To watch this short your mobile device can't be connected to this tv"

**To Reproduce**
Play any YouTube Short in TV

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker

**Apple TV (please complete the following information):**
 - Device: Apple TV 4K
 - OS: tvOS 17.0

**Additional context**
It seems that the latest version simulating a mobile device to skip ads is the issue, no problem on the older version that used YouTube API

**Comment by oxixes** [comment] 2023-10-24 10:01
Duplicate of #72

**Closed** 2023-10-24 10:03 UTC
Labels: bug

**Comment by dmunozv04** [comment] 2023-10-24 10:23
V1 actually used pyatv to control the tv, and the YouTube V3 api just to get the video id from the title and name of the channel currently playing. I suppose you'd be able to go back and use an older version if you really wanted to.

**Comment by dmunozv04** [comment] 2023-10-24 10:43
I didn't use version tags on V1, but you should be able to point to a specific docker image with its hash. All versions can be seen [here](https://github.com/dmunozv04/iSponsorBlockTV/pkgs/container/isponsorblocktv/versions). The latest V1 version seems to be [this one](https://github.com/dmunozv04/iSponsorBlockTV/pkgs/container/isponsorblocktv/97689499). That said, this isn't recommended

**Comment by L041S** [comment] 2023-10-24 11:08
Thank you it did the trick !
I will keep this setup until YouTube change this nonsense or just remove shorts
